<?php

include_once('panopoly_core.features.inc');

/**
 * Implements hook_page_build().
 */
function panopoly_core_page_build(&$page) {
  // This fixes a bug that causes @font-face declarations to break in IE6-8.
  // @see http://www.smashingmagazine.com/2012/07/11/avoiding-faux-weights-styles-...
  $path = drupal_get_path('module', 'panopoly_core');
  drupal_add_css($path . '/css/panopoly-fonts-ie-open-sans.css', array('group' => CSS_THEME, 'every_page' => TRUE, 'browsers' => array('IE' => 'lte IE 8', '!IE' => FALSE), 'preprocess' => FALSE));
  drupal_add_css($path . '/css/panopoly-fonts-ie-open-sans-bold.css', array('group' => CSS_THEME, 'every_page' => TRUE, 'browsers' => array('IE' => 'lte IE 8', '!IE' => FALSE), 'preprocess' => FALSE));
  drupal_add_css($path . '/css/panopoly-fonts-ie-open-sans-italic.css', array('group' => CSS_THEME, 'every_page' => TRUE, 'browsers' => array('IE' => 'lte IE 8', '!IE' => FALSE), 'preprocess' => FALSE));
  drupal_add_css($path . '/css/panopoly-fonts-ie-open-sans-bold-italic.css', array('group' => CSS_THEME, 'every_page' => TRUE, 'browsers' => array('IE' => 'lte IE 8', '!IE' => FALSE), 'preprocess' => FALSE));
}

/**
 * Implements hook_preprocess_html().
 *
 * We are telling the site that everything is a region-content. This is
 * important since when we disable the block module it loses this classes which
 * some things assume for generalized CSS considerations (i.e. Bartik's spacing
 * of ul/ol).
 */
function panopoly_core_preprocess_html(&$variables) {
  $variables['classes_array'][] = 'region-content';
}

/**
 * Implementation hook_element_info_alter().
 */
function panopoly_core_element_info_alter(&$type) {
  // Rather than implementing hook_css_alter(), we'll add a custom pre render
  // function for the styles elemement. This is to allow us to override
  // seven_css_alter(), which always runs after any module's implementation.
  if (isset($type['styles']['#pre_render'])) {
    array_unshift($type['styles']['#pre_render'], 'panopoly_core_pre_render_styles');
  }
}

/**
 * Pre render the styles element.
 */
function panopoly_core_pre_render_styles($elements) {
  $css = &$elements['#items'];

  // Installs the jQuery.UI themeroller theme to the theme.
  if (isset($css['misc/ui/jquery.ui.theme.css'])) {
    $css['misc/ui/jquery.ui.theme.css']['data'] = drupal_get_path('module', 'panopoly_core') . '/css/panopoly-jquery-ui-theme.css';
  }

  if (isset($css['misc/ui/jquery.ui.dialog.css'])) {
    unset($css['misc/ui/jquery.ui.dialog.css']);
  }

  if (isset($css['misc/ui/jquery.ui.tabs.css'])) {
    unset($css['misc/ui/jquery.ui.tabs.css']);
  }

  return $elements;
}

/**
 * Implements hook_date_format_types().
 */
function panopoly_core_date_format_types() {
  return array(
    'panopoly_time' => t('Time'),
    'panopoly_day' => t('Day'),
  );
}

/**
 * Implements hook_date_formats().
 */
function panopoly_core_date_formats() {
  $formats = array();

  $formats[] = array(
    'type' => 'panopoly_time',
    'format' => 'g:ia',
    'locales' => array(),
  );

  $formats[] = array(
    'type' => 'panopoly_day',
    'format' => 'F j, Y',
    'locales' => array(),
  );

  return $formats;
}

/**
 * Helper function to get node view modes.
 */
function panopoly_core_view_mode_options() {
  $entity_info = entity_get_info('node');
  $options = array();
  if (!empty($entity_info['view modes'])) {
    foreach ($entity_info['view modes'] as $mode => $settings) {
      if (!in_array($mode, array('rss', 'search_index', 'search_result', 'token'))) {
        $options[$mode] = $settings['label'];
      }
    }
  }
  return $options;
}
